<p class="text-center">Bienvenue sur la page d'administration</p>
<section id="admin-card" class="row">
    <div class="card col-4 p-0">
        <a href="?page=adminmonstretab">
            <img src="./assets/mh_img/tabMonstre.jpg" class="card-img" alt="...">
        </a>
        <h5 class="card-title text-center admin-card-title">Voir les monstres</h5>
    </div>
    <div class="card col-4 p-0">
        <a href="?page=admin_add_monstre">
            <img src="./assets/mh_img/addMonster.jpg" class="card-img" alt="...">
        </a>
        <h5 class="card-title text-center admin-card-title">Ajouter un monstre</h5>
    </div>
        <div class="card col-4 p-0">
        <a href="?page=admin_users_tab">
            <img src="./assets/mh_img/users.jpg" class="card-img" alt="...">
        </a>
        <h5 class="card-title text-center admin-card-title">Voir les users</h5>
    </div>
</section>