<?php 
$user = $data['user'];
$state = $data['state'];
?>


<section id="contact" class="p-3">
    <h1>Edit User</h1>
    <form class="row g-3" action="?page=adminuseredit<?php echo "&id=".$_GET['id']; ?>" method="POST">
        <div class="col-md-6">
            <label for="inputNom" class="form-label">Firstname</label>
            <input type="text" class="form-control" id="inputNom" name="firstname" value="<?= $user['firstname'] ?>" required>
        </div>
        <div class="col-md-6">
            <label for="inputPrenom" class="form-label">Lastname</label>
            <input type="text" class="form-control" id="inputPrenom" name="lastname" value="<?= $user['lastname'] ?>" required>
        </div>
        <div class="col-md-6">
            <label for="inputEmail4" class="form-label">Email</label>
            <input type="email" class="form-control" id="inputEmail4" name="email" value="<?= $user['email'] ?>" required>
        </div>
        <div class="col-md-6">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" value="<?= $user['username'] ?>" required>
        </div>
        <div class="col-md-6">
            <p> Roles :
                <input class="form-check-input" type="checkbox" value="ROLE_ADMIN" name="roles[]" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    Admin
                </label>
            </p>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">Address</label>
            <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St" value="<?= $user['address1'] ?>" name="address1">
        </div>
        <div class="col-12">
            <label for="inputAddress2" class="form-label">Address 2</label>
            <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor" value="<?= $user['address2'] ?>" name="address2">
        </div>
        <div class="col-md-6">
            <label for="inputCity" class="form-label">City</label>
            <input type="text" class="form-control" id="inputCity" value="<?= $user['city'] ?>" name="city">
        </div>
        <div class="col-md-4">
            <label for="inputState" class="form-label">State</label>
            <select id="inputState" class="form-select" name="state">
            <?php foreach($state as $s) :?>
            <option <?php if($user['state'] == $s) {echo "selected";} ?>><?= $s ?></option>
            <?php endforeach; ?>
            </select>
        </div>
        <div class="col-md-2">
            <label for="inputZip" class="form-label">Zip</label>
            <input type="text" class="form-control" id="inputZip" value="<?= $user['zip'] ?>" name="zip">
        </div>
        <div class="col-12">
            <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck" name="check" required>
            <label class="form-check-label" for="gridCheck">
                Check me out
            </label>
            </div>
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </form>
    
    
</section>

