<?php
$els = $data['els'];
$monstre = $data['monstre'];
$favori = $data['favori'];
$commentaires = $data['commentaires'];
$id = $data['id'];
?>
<section v-if="getCurrentLivre != null" class="container py-5">
    <article class="row">
        <section class="col-lg-6">
            <img src = "<?= $monstre['img'] ?>" class="img-fluid" alt="Product Image" style="height: 500px" />
        </section>
        <section class="col-lg-6 d-flex flex-column justify-content-between">
            <div>
                <div class="d-flex align-items-center">
                <h2 class="fw-bold"> <?= $monstre['nom'] ?></h2>
                <?php if(App\Services\Utils::isUserConnected()) : ?>
                <div class="text-end ms-auto">
                    <input type="checkbox" id="heart" class="heart_check" onclick="addFavourite()" <?php if(in_array($id,$favori)) echo "checked" ?>/>
                    <label for="heart" class="heart_label">
                        Favori
                    </label>
                </div>
                <?php endif; ?>
                </div>
                <p class="text-muted"><?= $monstre['categorie'] ?> apparue dans la <?php echo $monstre['generation']; echo $monstre['generation'] == 1 ? 'er' : 'ème' ?> genération</p>
                <p><?= $monstre['short_description'] ?></p>
            </div>
            <div class="d-flex align-items-center w-100 align-items-end" >
                <div class="card w-50 text-center">
                    <h5 class="class-header ">Elements</h5>
                    <div class="card-body">
                        <p>
                            <?php foreach($els as $el) :  if(in_array($el[0],json_decode($monstre['elements']))) : ?>
                                <?= $el[1] ?>
                            <?php endif; endforeach; ?>
                        </p>
                    </div>
                </div>
                <div class="card w-50 text-center">
                    <h5 class="class-header">Faiblesses</h5><br>
                    <div class="card-body">
                        <p>
                            <?php foreach($els as $el) :  if(in_array($el[0],json_decode($monstre['faiblesses']))) : ?>
                                <?= $el[1] ?>
                            <?php endif; endforeach; ?>
                        </p>
                    </div>
                </div>
            </div>
        </section>
    </article>
    <aside>
    <ul class="nav nav-tabs mt-5" id="productTab" role="tablist">
        <li class="nav-item" role="presentation">
        <button class="nav-link <?= !isset($_GET['commentaire_id']) ? 'active" aria-selected="true"' : ' aria-selected="false' ?>" id="description-tab" data-bs-toggle="tab" data-bs-target="#description" type="button" role="tab" aria-controls="description" >
            Description
        </button>
        </li>
        <li class="nav-item" role="presentation">
        <button class="nav-link" id="specs-tab" data-bs-toggle="tab" data-bs-target="#specs" type="button" role="tab" aria-controls="specs" aria-selected="false">
            Specifications
        </button>
        </li>
        <li class="nav-item" role="presentation">
        <button class="nav-link <?= isset($_GET['commentaire_id']) ? 'active" aria-selected="true"' : ' aria-selected="false' ?>"id="reviews-tab" data-bs-toggle="tab" data-bs-target="#reviews" type="button" role="tab" aria-controls="reviews" >
            Reviews
        </button>
        </li>
        <?php if(App\Services\Utils::isRole('ROLE_MEMBER')) : ?>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="ajout-tab" data-bs-toggle="tab" data-bs-target="#ajout" type="button" role="tab" aria-controls="ajout" aria-selected="false">
                Ajouter un commentaire
            </button>
        </li>
        <?php endif; ?>
    </ul>
    <div class="tab-content" id="productTabContent">
        <div class="tab-pane fade <?php if(!isset($_GET['commentaire_id'])) echo 'show active'; ?>" id="description" role="tabpanel" aria-labelledby="description-tab"
        >
            <p class="mt-3">
                <?= $monstre['description'] ?>
            </p>
        </div>
        <div class="tab-pane fade" id="specs" role="tabpanel" aria-labelledby="specs-tab">
            <table class="table mt-3">
                <tr>
                    <th>Taille minimum :</th>
                    <td><?= json_decode($monstre['taille'])[0] ?> cm</td>
                </tr>
                <tr>
                    <th>Taille maximum :</th>
                    <td>👑<?= json_decode($monstre['taille'])[1] ?> cm</td>
                </tr>
            </table>
        </div>
        <div class="tab-pane fade <?php if(isset($_GET['commentaire_id'])) echo 'show active'; ?>" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
            <div class="mt-3">
                
                <?php foreach($commentaires as $commentaire) : ?>
                    <div class="d-flex">
                        <div class="me-3">
                            <a href="?page=profil&id=<?= $commentaire['user_id'] ?>"><img src="<?= $commentaire['avatar']; ?>" class="rounded-circle" height="44" alt="Avatar" class="avatar"/></a>
                        </div>
                        <div class="w-100">
                            <h5>@<?= $commentaire['username'] ?></h5>
                            <?php if(isset($_GET['commentaire_id']) && $_GET['commentaire_id'] == $commentaire['id'] && App\Services\Utils::isUserConnected() && (App\Services\Utils::isRole('ROLE_ADMIN') || $commentaire['user_id'] == $_SESSION['user']['id'])) : ?>
                            <form action="?page=monstredetails&id=<?= $monstre['id'] ?>&commentaire_id=<?= $commentaire['id'] ?>" method="POST">
                                <textarea class="form-control" name="commentaire" id="commentaire" cols="30" rows="4" placeholder="Ajouter un commentaire" required><?= $commentaire['commentaire'] ?></textarea>
                                <button type="submit" class="btn btn-primary">Valider</button>
                            </form>
                            <?php else : ?>
                            <p><?= $commentaire['commentaire'] ?></p>
                            <?php endif; ?>
                            <p><?= $commentaire['posted_at'] ?></p>
                        </div>
                        <?php if(App\Services\Utils::isUserConnected() && (in_array('ROLE_ADMIN',json_decode($_SESSION['user']['roles'])) || $commentaire['user_id'] == $_SESSION['user']['id'])) : ?>
                            <form action="?page=monstredetails&id=<?= $monstre['id'] ?>&commentaire_id=<?= $commentaire['id'] ?>" method="POST"><button type="submit" class="btn btn-primary">Modifier</button></form>
                            <form action="?page=delete&tab=commentaire&commentaire_id=<?= $commentaire['id'] ?>&id=<?= $monstre['id'] ?>" method="POST"><button type="submit" class="btn btn-danger">Supprimer</button></form>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="tab-pane fade" id="ajout" role="tabpanel" aria-labelledby="ajout-tab">
            <form action="?page=monstredetails&id=<?= $monstre['id'] ?>" method="POST">
                <div class="mb-3">
                    <div class="form-floating">
                        <textarea class="form-control" placeholder="Leave a comment here" id="ajoutText" name="message" style="height: 100px"></textarea>
                        <label for="floatingTextarea2">Commentaire</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </form>
        </div>
    </div>
    </aside>
</section>
<script>
    function addFavourite(){
        const heart = document.getElementById('heart');
        
        if(heart.checked === true){
            const xhr = new XMLHttpRequest();
            xhr.open("GET", "?page=monstredetails&id=" + <?= $monstre['id'] ?> + "&heart=true", true);
            xhr.onreadystatechange = function() {
                if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
                    var response = xhr.responseText;
                    // Code to handle the response goes here
                }
            };
            xhr.send();
            console.log(xhr)
        }
        else{
            const xhr = new XMLHttpRequest();
            xhr.open("GET", "?page=monstredetails&id=" + <?= $monstre['id'] ?> + "&heart=false", true);
            xhr.onreadystatechange = function() {
                if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
                    var response = xhr.responseText;
                    // Code to handle the response goes here
                }
            };
            xhr.send();
            console.log(xhr)
        }
    }
</script>
