<?php
    $err_login = '';
    if(isset($_SESSION['err_login']) && !empty($_SESSION['err_login'])){
        $err_login = $_SESSION['err_login'];
        unset($_SESSION['err_login']);
    }
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo CONFIG_SITE_TITLE; ?></title>
    <link rel="stylesheet" href="./assets/css/main.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
    $(document).ready(function() {
        <?php if(!empty($err_login)) : ?>
            $("#user-login").modal('show');
        <?php endif; ?>
    })
</script>
</head>
<body class="min-vh-100">
    <header>
        <nav class="navbar navbar-expand-lg mh_nav" data-bs-theme="black">
            <div class="container-fluid">
                <a class="navbar-brand" href="?page=home"><img class="logo" src="./assets/logo/logo_mh.png"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] == 'home') echo 'active'; ?>" aria-current="page" href="?page=home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] == 'gallery') echo 'active'; ?>" href="?page=gallery">Galerie</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] == 'contact') echo 'active'; ?>" href="?page=contact">Contact</a>
                    </li>
                    <?php if (isset($_SESSION['user']['roles']) && in_array('ROLE_ADMIN', json_decode($_SESSION['user']['roles']))) : ?>
                    <li class="nav-item">
                        <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] == 'admin') echo 'active'; ?>" href="?page=admin">Admin</a>
                    </li>
                    <?php endif; ?>
                </ul>
                <?php if(isUserConnected()) : ?>
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="<?= $_SESSION['user']['avatar']; ?>" class="rounded-circle" height="66" alt="Avatar" class="avatar"/>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="?page=profil&id=<?= $_SESSION['user']['id']; ?>">Profil</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="?page=logout">Logout</a></li>
                    </ul>
                </div>
                <?php else : ?>
                    <button class="button-78" role="button" id="login" data-bs-toggle="modal" href="#user-login">Login</button>
                <?php endif; ?>
                <form class="d-flex" role="search">
                    <input name="page" value="gallery" type="hidden">
                    <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="button-78" role="submit">Search</button>
                </form>
                </div>
            </div>
            
        </nav>
    </header>
    <?php include "./modals/modal_login.php"; ?>
    <?php include "./views/template_" . $page . ".phtml"; ?>
    <footer>
    <article class=" bg-dark text-light mb-0">
        <h1>How to be a wizard</h1>
        <ol>
            <li>Grow a long, majestic beard.</li>
            <li>Wear a tall, pointed hat.</li>
            <li>Have I mentioned the beard?</li>
        </ol>
            <p class="mb-0">© 2018 Gandalf</p>
        </footer>
    </article>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>