<section id="register" class="p-3">
    <?php if (isset($errors) && !empty($errors)) : ?> 
    <?php foreach($errors as $error):  ?>
        <div class="alert alert-danger" role="alert">
        <?php echo $error; ?>
        </div>
    <?php endforeach; ?>
    <?php endif; ?>
    <h1>Inscription</h1>
    <?php if (!$success) : ?>
    <form class="row g-3" action="?page=register" method="POST" enctype="multipart/form-data">
        <div class="col-md-6">
            <label for="inputNom" class="form-label">Firstname</label>
            <input type="text" class="form-control" id="inputNom" name="firstname" required>
        </div>
        <div class="col-md-6">
            <label for="inputPrenom" class="form-label">Lastname</label>
            <input type="text" class="form-control" id="inputPrenom" name="lastname" required>
        </div>
        <div class="col-md-6">
            <label for="inputEmail4" class="form-label">Email</label>
            <input type="email" class="form-control" id="inputEmail4" name="email" required>
        </div>
        <div class="col-md-6">
            <label for="inputPassword4" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputPassword4" name="password" required>
        </div>
        <div class="col-md-6">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="col-md-6">
            <label for="inputPassword4" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="inputPassword4" name="confirmPassword" required>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">Address</label>
            <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St" name="address1">
        </div>
        <div class="col-12">
            <label for="inputAddress2" class="form-label">Address 2</label>
            <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor" name="address2">
        </div>
        <div class="col-md-6">
            <label for="inputCity" class="form-label">City</label>
            <input type="text" class="form-control" id="inputCity" name="city">
        </div>
        <div class="col-md-4">
            <label for="inputState" class="form-label">State</label>
            <select id="inputState" class="form-select" name="state">
            <option selected >Choose...</option>
            <?php foreach($state as $s) {echo "<option>$s</option>";} ?>
            </select>
        </div>
        <div class="col-md-2">
            <label for="inputZip" class="form-label">Zip</label>
            <input type="text" class="form-control" id="inputZip" name="zip">
        </div>
        <div class="col-3">
            <input type="file" class="form-control" id="inputZip" name="avatar">
        </div>
        <div class="col-12">
            <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck" name="check" required>
            <label class="form-check-label" for="gridCheck">
                Check me out
            </label>
            </div>
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </form>
    <?php else: ?>
        <div class="alert alert-success" role="alert">
        <p> Votre compte à été crée avec succèss. </p>
        <p> Vous pouvez <a href="?page=login">vous connecter</a></p>
        </div>
    <?php endif; ?>
    
    
</section>

